server:
  #asigna un puerto que se encuentre sin uso automaticamente
  port: ${PORT:${SERVER_PORT:0}}
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: maracaibo2360
    driverClassName: org.postgresql.Driver
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:${spring.application.instance_id:${random.value}}
      #instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}:${spring.application.instance_id:${random.value}}
      #instance:
      #instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
      #instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#servidor
#server.port=8002
#spring.application.name=carro-service
#BD
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=maracaibo2360
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#Primera vez para crear tablas
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true